name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file ./devops_essentials/docker-alpine-extended/Dockerfile --tag ghcr.io/jrjuanj01/my-docker-image:latest
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push Docker image to registry
      run: docker push ghcr.io/jrjuanj01/my-docker-image:latest
